include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    file_names: ignore
    non_constant_identifier_names: ignore
    strict_top_level_inference: ignore
    use_build_context_synchronously: ignore
